# yaml-language-server: $schema=https://json.schemastore.org/chart.json
apiVersion: v2
type: application
name: prometheus
description: A Helm chart for prometheus
version: 1.3.8
# renovate: image=prom/prometheus
appVersion: "v2.44.0"
deprecated: true

home: https://charts.pascaliske.dev/charts/prometheus/
sources:
  - https://github.com/pascaliske/helm-charts
  - https://github.com/prometheus/prometheus
  - https://prometheus.io
keywords:
  - prometheus
  - metrics

annotations:
  artifacthub.io/changes: |-
    - kind: removed
      description: 'Remove values schema due to issues with flux variable substitution.'
