{{- if and .Values.secret.create (empty .Values.secret.existingSecret) -}}
{{- if empty .Values.secret.token -}}
  {{- fail "Missing token from \".Values.secret.token\"!" -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-token" (include "cloudflare-dyndns.fullname" .) }}
  labels:
    {{- include "cloudflare-dyndns.labels" . | nindent 4 }}
    {{- with .Values.secret.labels }}
    {{ toYaml . | indent 4 }}
    {{- end }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  CF_API_TOKEN: {{ .Values.secret.token | b64enc }}
{{- end -}}
