name: Release Charts
concurrency: release-charts
on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'

permissions:
  contents: write
  packages: write

jobs:
  release:
    name: Release Charts
    runs-on: ubuntu-latest
    steps:
      # checkout
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0

      # setup helm
      - uses: azure/setup-helm@dda3372f752e03dde6b3237bc9431cdc2f7a02a2 # v5.0.0
        with:
          version: v3.21.1

      # setup taskfile
      - uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611 # v2.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      # setup cache for social cards
      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          key: ${{ github.ref }}
          path: .cache

      # configure git
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      # deploy charts to github pages
      - uses: helm/chart-releaser-action@cae68fefc6b5f367a0275617c9f83181ba54714f # v1.7.0
        id: cr
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CR_GENERATE_RELEASE_NOTES: true
          CR_SKIP_EXISTING: true

      # setup access to container registry
      - uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        if: ${{ steps.cr.outputs.changed_charts }}
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # push charts to container registry
      - name: Push charts to container registry
        if: ${{ steps.cr.outputs.changed_charts }}
        run: |
          for CHART in .cr-release-packages/*; do
            if [ -z "${CHART:-}" ]; then break; fi
            helm push "${CHART}" oci://ghcr.io/${{ github.repository }}
          done

      # create pages for docs
      - name: Create pages for docs
        run: task docs
        env:
          PROD_DOMAIN: ${{ secrets.PROD_DOMAIN }}

      # deploy docs
      - uses: mhausenblas/mkdocs-deploy-gh-pages@a31c6b13a80e4a4fbb525eeb7a2a78253bb15fa5 # master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REQUIREMENTS: docs/requirements.txt
